#!/usr/bin/env ts-node

import chapters from './meta/chapters.json'
import { writeOutput } from './helpers'

type RedirectRule = {
  redirect: {
    to: string
    statusCode: 301
  }
}

const configs: Record<string, RedirectRule> = {}

for (const chapter of chapters) {
  const { slug, articlesCount } = chapter

  if (articlesCount > 1) {
    configs[`/artikel/${slug}`] = {
      redirect: {
        to: `/artikel/${slug}/01`,
        statusCode: 301
      }
    }
  }
}

const routeRulesPath = './pug-to-md/generated/route-rules.ts'
const routeRulesModule = `// This file is auto-generated by pug-to-md/redirects.ts.
// Do not edit manually.

const routeRules = ${JSON.stringify(configs, null, 2)} as const

export default routeRules
`

writeOutput(routeRulesModule, routeRulesPath)
