#!/usr/bin/env ts-node

import fs from 'node:fs'
import path from 'node:path'
import process from 'node:process'
import chapters from './meta/chapters.json'

type RedirectRule = {
  redirect: {
    to: string
    statusCode: 301
  }
}

const configs: Record<string, RedirectRule> = {}

for (const chapter of chapters) {
  const { slug, articlesCount } = chapter

  if (articlesCount > 1) {
    configs[`/${slug}`] = {
      redirect: {
        to: `/${slug}/01`,
        statusCode: 301
      }
    }
  }
}

const routeRulesPath = './pug-to-md/generated/route-rules.ts'
const routeRulesModule = `// This file is auto-generated by pug-to-md/redirects.ts.
// Do not edit manually.

const routeRules = ${JSON.stringify(configs, null, 2)} as const

export default routeRules
`

writeOutput(routeRulesModule, routeRulesPath)

function writeOutput(text: string, outputPath?: string) {
  if (outputPath) {
    try {
      fs.mkdirSync(path.dirname(outputPath), { recursive: true })
      fs.writeFileSync(outputPath, text, 'utf8')
      console.log(`File written: ${outputPath}`)
    } catch (err) {
      console.error(`Failed to write output file: ${outputPath}`)
      console.error(err)
      process.exit(1)
    }
  } else {
    process.stdout.write(text + '\n')
  }
}
